/*******************************************************************************
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * There is no copyright registered for following awesome work.
 * Whatever contributed here is not private but do no copy. Instead
 * collaborate and spread knowledge. 
 *******************************************************************************/
package com.anverm.login.session;

/**
 * @author anand
 * <a href="mailto:anand.vrm88@gmail.com">Anand Verma</a>$
 * Created on: 03-Oct-2014
 */
public class UserSession {
  private int sessionId;
  private String token;
  private String appURL;
  private String userName;
  private long creationTime;
  private long lastActiveTime;
  
  /**
   * @param sessionId id generated by login server.
   * @param token unique key which in future can be used for authentication.  
   * @param userName contains user details like first name
   * last name and email id.
   */
  public UserSession(int sessionId, String token, String userName) {
    super();
    this.sessionId = sessionId;
    this.token = token;
    this.userName = userName;
  }


  public int getSessionId() {
    return sessionId;
  }
  
  public String getToken() {
    return token;
  }

  public String getAppURL() {
    return appURL;
  }

  public String getUserName() {
    return userName;
  }

  public long getCreationTime() {
    return creationTime;
  }

  public long getLastActiveTime() {
    return lastActiveTime;
  }
  
}
